### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by ItsDavehere** [F0RIS/Ogar-servers-manager#1]
does this works for MultiOgar thanks .

**Comment by F0RIS** [comment]
Fetching data from servers made via json, so it can work with ogar, ogar_unlimited and of course multiogar

**Comment by F0RIS** [comment]
@ItsDavehere if you will take this code for something and make some changes, can you upload your changes in your own repo in github or even make pull requests to this repo

**Comment by ItsDavehere** [comment]
@F0RIS thanks that helps alot, Great repo.
